### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gshepperd** [gjr80/weewx-bloomsky#2]
It worked one time, now I'm getting this in my syslog:
Apr 12 12:18:01 raspberrypi weewx[1124]: bloomsky: bloomsky-client: Exception:
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****  Traceback (most recent call last):
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****    File "/usr/share/weewx/user/bloomsky.py", line 674, in run
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****      self.client.collect_data()
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****    File "/usr/share/weewx/user/bloomsky.py", line 483, in collect_data
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****      raw_data = self.sd.get_data()
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****    File "/usr/share/weewx/user/bloomsky.py", line 698, in get_data
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****      params, headers)
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****    File "/usr/share/weewx/user/bloomsky.py", line 742, in get_request
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****      "Failed to get BloomSky API data")
Apr 12 12:18:01 raspberrypi weewx[1124]:     ****  TypeError: logerr() takes exactly 1 argument (2 given)
Apr 12 12:18:02 raspberrypi weewx[1124]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Apr 12 12:18:02 raspberrypi weewx[1124]: manager: Starting backfill of daily summaries

**Comment by gjr80** [comment]
Thanks for the report, please try [v1.0.1](https://github.com/gjr80/weewx-bloomsky/releases/tag/v1.0.1). This will fix the `TypeError` you experienced though I suspect there may well be a further issue that is preventing you from getting data from the Bloomsky API, or perhaps it was a one off issue with the API. Let me know if anything further comes up after you install v1.0.1.

**Comment by gjr80** [comment]
Closing, nothing further heard. Can be reopened if required.
