### ISSUE TITLE
New Install Errors 

### ISSUE THREAD

**Issue by stevefnz** [gjr80/weewx-bloomsky#3]
Hi
New install on a pi3 with rasp os lite , all seemed ok except these errors ?
Thanks
Stephen
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****      __import__(driver)
Jul 26 10:17:00 raspberrypi weewx[4913]: Starting weewx weather system: weewx.
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****    File "/usr/share/weewx/user/bloomsky.py", line 1003
Jul 26 10:17:00 raspberrypi systemd[1]: Started LSB: weewx weather system.
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****      print "Using configuration file %s" % config_path
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****                                        ^
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****  SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Using config         uration file %s" % config_path)?
Jul 26 10:17:00 raspberrypi weewx[4928] CRITICAL __main__:     ****  Exiting.
Jul 26 10:17:01 raspberrypi CRON[4953]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by gjr80** [comment]
Turns out there is good news and bad. The good is that I had already reworked the driver for WeeWX 4/python2/3 but just never got around to releasing it. The bad news is that my Bloomsky failed a few months back and I am unable to fully test the driver. So if you don't mind being the guinea pig...

To use the new driver:
1. move your current driver aside:
```
$ sudo mv /usr/share/weewx/user/bloomsky.py /usr/share/weewx/user/bloomsky_orig.py
```
2. download the new driver:
```
$ sudo wget -P /usr/share/weewx/user https://raw.githubusercontent.com/gjr80/weewx-bloomsky/python3/bin/user/bloomsky.py
```
3. try running the driver directly, the following will show you the driver help:
```
$ PYTHONPATH=/usr/share/weewx python -m user.bloomsky --help
```
depending on your system you may need to explicitly run the driver under python3 by changing `python` to `python3` in the above command

Assuming the above command executes OK try running `--get-device-ids`, `--get-json-data` and `--test-driver`. Note that provided your API key is in `weewx.conf` there is no need to specify it on the command line with `--api-key`. If these don't work as expected check the WeeWX log. If that doesn't help at all run the command(s) again but this time add `--debug=3` to the command line and post the console output (including the command entered) **_and_** the corresponding log output.

There might be a bit of toing and froing here, orry to put you to this trouble but it is a bit hard to test the driver without a working Bloomsky setup.

Thanks.

**Comment by stevefnz** [comment]
Cool ! Yep I’ll test it tonight and advise :)

Regards Stephen F


On 27/07/2020, at 17:34, gjr80 <notifications@github.com> wrote:

﻿

Turns out there is good news and bad. The good is that I had already reworked the driver for WeeWX 4/python2/3 but just never got around to releasing it. The bad news is that my Bloomsky failed a few months back and I am unable to fully test the driver. So if you don't mind being the guinea pig...

To use the new driver:

  1.  move your current driver aside:

$ sudo mv /usr/share/weewx/user/bloomsky.py /usr/share/weewx/user/bloomsky_orig.py


  1.  download the new driver:

$ sudo wget -P /usr/share/weewx/user https://raw.githubusercontent.com/gjr80/weewx-bloomsky/python3/bin/user/bloomsky.py


  1.  try running the driver directly, the following will show you the driver help:

$ PYTHONPATH=/usr/share/weewx python -m user.bloomsky --help


depending on your system you may need to explicitly run the driver under python3 by changing python to python3 in the above command

Assuming the above command executes OK try running --get-device-ids, --get-json-data and --test-driver. Note that provided your API key is in weewx.conf there is no need to specify it on the command line with --api-key. If these don't work as expected check the WeeWX log. If that doesn't help at all run the command(s) again but this time add --debug=3 to the command line and post the console output (including the command entered) and the corresponding log output.

There might be a bit of toing and froing here, orry to put you to this trouble but it is a bit hard to test the driver without a working Bloomsky setup.

Thanks.

**Comment by stevefnz** [comment]
Perfect !

Worked , all those commands were effective

I have just found out my SKY has gone off line again :( , damn thing loses wifi , but the storm is still there and it is definitely retrieving all the data from the API , temps etc are wrong due to sky but ill fix that in a few days as its offsite , but overall great job ! Thanks !

PYTHONPATH=/usr/share/weewx python3 -m user.bloomsky --test-driver
Using configuration file /etc/weewx/weewx.conf
2020-07-27 19:31:28 NZST (1595835088) {'dateTime': 1595835088, 'usUnits': 17, 'deviceID': '442C053A1055', 'd                                                             eviceName': 'Pikes Point', 'outTemp': 9999.0, 'txBatteryStatus': 0.0, 'outHumidity': 9999, 'imageURL': 'http                                                             ://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsmKKlmJqnqJ1lq52ul5SqmpU=.jpg', 'deviceType': 'SKY2', 'night':                                                              False, 'imageTimestamp': 1558723620, 'rainRate': 0.0, 'windSpeed': 0.0, 'windDir': 135, 'windGust': 0.0, 'r                                                             ainDaily': 0.2, 'rain': None}
2020-07-27 19:32:29 NZST (1595835149) {'dateTime': 1595835149, 'usUnits': 17, 'deviceID': '442C053A1055', 'd                                                             eviceName': 'Pikes Point', 'outTemp': 9999.0, 'txBatteryStatus': 0.0, 'outHumidity': 9999, 'imageURL': 'http                                                             ://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsmKKlmJqnqJ1lq52ul5SqmpU=.jpg', 'deviceType': 'SKY2', 'night':                                                              False, 'imageTimestamp': 1558723620, 'rainRate': 0.0, 'windSpeed': 0.0, 'windDir': 135, 'windGust': 0.0, 'r                                                             ainDaily': 0.2, 'rain': 0.0}

**Comment by gjr80** [comment]
Good, I had a nagging doubt in my mind that I had not completed the conversion and there would be issues, it was some eight months ago that I last worked on the code. I will release this as v2.0.0, up to you if you want to install the released code, only change will changing 2.0.0b1 to 2.0.0.

Let us know if any problems when your Sky is working, I suspect there won't be since the driver is correctly receiving and decoding other data.

**Comment by gjr80** [comment]
Have published v2.0.0 release. Will close this for now, can be re-opened if further problems occur.

**Comment by stevefnz** [comment]
Hi

I got my sky up and running and it all seems good so thanks again !

Is there anyway I can get the current webcam image from the bloomsky , I worked out that you retrieve the url from the API , but I can’t work out Is that somewhere I can use it ? , I am running the weather 34 template so I guess it would need the image to be ftp somewhere as a std name which I could do if I knew how to get the current url somewhere 😊

Thanks

**Comment by gjr80** [comment]
Hi,

Good that it is all working. Yes the image URL should be picked up by the driver but how you use it, well that depends on how you want to use it!. For example, if you wanted to put the URL in a WeeWX generated report it is pretty easy, you should be able to use the tag (untested) `$current.imageURL`. So if you had a link in a html page that you wanted to populate you could include something like this in the `.tmpl` file:
```
<a  href="$current.imageURL">
```

or to display the actual image (again untested):
```
<img src="$current.imageURL" alt="Current Bloomsky image" />
```

If you need to use the URL in some other way (ie not in a WeeWX generated report) then that is a bit more complex and may require some python or other trickery.

I am not familiar with the weather 34 templates so I can't advise you on exactly what you need do to incorporate the image URL. But Ian Steeple (the Weather 34 WeeWX template maintainer) is pretty helpful, drop him a line or post an issue on his Weather 34 GitHub page or post something on weewx-user and he should get back to you.

**Comment by stevefnz** [comment]
Hi

Yep thanks for the info

I have taken a copy of your python to see if I could write a local file that contained the image on each retrieval from the API

Then I could just periodically ftp that file to the webserver and then it all just works with the skins

So basically just overwriting a single file each time , like say bloomsky.jpg

I used to program long ago but not python , but ill have a go 😊 , im trying to retrieve the file from the url when you do the translate section …. I figured the data from the url is available at the point



Thanks again

Stephen Farmer

Mobile +64-21-227-5079
Email stephen@downforce.co.nz<mailto:stephen@downforce.co.nz>
[Description: Downforce med]<http://www.downforce.co.nz/>
30 Angle Street, Onehunga, Auckland, 1061, New Zealand <  PO Box 42153, Orakei, Auckland 1745  <  www.downforce.co.nz<http://www.downforce.co.nz/>

**Comment by stevefnz** [comment]
Hi again

I actually did get it to work , so in case it is of use for u this is what I did so that it writes a copy of the image into a standard file in the html directory which can then be ftp or used as reqd

Anyway feel free to incorporate or change as u see fit , given my python experience of 2 days 😊

# Import for Image Retrieval
import requests # to get image from the web
import shutil # to save it locally
import os

TRANSLATIONS = {'Data': {'Voltage': '_trans_voltage',
                             'UVIndex': '_trans_uv',
                             'Luminance': '_trans_luminance',
                             'ImageURL': '_trans_image'
                             },


@staticmethod
    def _trans_image(data, key):
        # retrieve url file and save as std name
        if os.path.exists("/var/www/html/weewx/bloomskyimg.jpg"):
            os.remove("/var/www/html/weewx/bloomskyimg.jpg")
        else:
            print("The image file does not exist")
        ## Set up the image URL and filename
        image_url = data[key]
        print("Try url ",data[key])
        filename = "/var/www/html/weewx/bloomskyimg.jpg"

        # Open the url image, set stream to True, this will return the stream content.
        r = requests.get(image_url, stream = True)
        # Check if the image was retrieved successfully
        if r.status_code == 200:
           # Set decode_content value to True, otherwise the downloaded image file's size will be zero.
           r.raw.decode_content = True
           print('Image sucessfully Downloaded: ',filename)
           # Open a local file with wb ( write binary ) permission.
           with open(filename,'wb') as f:
               shutil.copyfileobj(r.raw, f)

           print('Image sucessfully written: ',filename)
        else:
           print('Image Couldn\'t be retreived')



Stephen Farmer

Mobile +64-21-227-5079
Email stephen@downforce.co.nz<mailto:stephen@downforce.co.nz>
[Description: Downforce med]<http://www.downforce.co.nz/>
30 Angle Street, Onehunga, Auckland, 1061, New Zealand <  PO Box 42153, Orakei, Auckland 1745  <  www.downforce.co.nz<http://www.downforce.co.nz/>
